import { Poppins } from "next/font/google";
import { Lobster } from "next/font/google";
import "./globals.css";
import Nav from "./_sections/Nav/page";
import { cn } from "@/lib/utils";
import Footer from "./_sections/Footer/page";

const lobster = Lobster({
  weight: "400",
  display: "swap",
  variable: "--font-lobster",
  subsets: ["latin"],
});

const poppins = Poppins({ weight: "400", subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={cn("max-w-screen-xl container", lobster.variable)}>
        <Nav />
        {children}
      </body>
    </html>
  );
}
